// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUNK03Vf2w0OuM_tLQ6LrML4AoFyjQ2LE',
    appId: '1:293881636945:web:138d2db2c6e98f98fbb070',
    messagingSenderId: '293881636945',
    projectId: 'notepad-716e1',
    authDomain: 'notepad-716e1.firebaseapp.com',
    storageBucket: 'notepad-716e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtqOBbuBjtFVC12W0XOq6ADg8J1H1TE_w',
    appId: '1:293881636945:android:d8c45ec78ef73b14fbb070',
    messagingSenderId: '293881636945',
    projectId: 'notepad-716e1',
    storageBucket: 'notepad-716e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjjjZ2hHNk_KPpcF3yKt03kN_uk7NB30',
    appId: '1:293881636945:ios:3597c6df9c2d98bafbb070',
    messagingSenderId: '293881636945',
    projectId: 'notepad-716e1',
    storageBucket: 'notepad-716e1.appspot.com',
    iosClientId: '293881636945-v3icolol2oeuuhi969brljlfv6a91lkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.notePad',
  );
}
